# lab3

## ![ex1.1](./tmp/Lab_3_ex1.1.png)

In [1]:
# exe 1.1
import numpy as np
v1 = np.array([1,3,5,7])
v2 = np.array([[0.5],[-2.1],[4.0]])
print ("le nombre de dimensions de v1 est", v1.ndim)
print("la forme de v1 est", v1.shape)
print ("le nombre d'éléments de v1 est", v1.ndim)
print("la forme de v2 est", v2.shape)


le nombre de dimensions de v1 est 1
la forme de v1 est (4,)
le nombre d'éléments de v1 est 1
la forme de v2 est (3, 1)


In [2]:
#exe 1.2
x= np.array([2,-1,0])
y = np.array([4,5,6])
dot_xy = np.dot(x,y)
print("le produit scalaire de x et y est", dot_xy)
dot2_xy = x@y 
print("le produit scalaire en utilisant l'opérateur @ de x et y est", dot2_xy)

le produit scalaire de x et y est 3
le produit scalaire en utilisant l'opérateur @ de x et y est 3


![ex2.1](./tmp/Lab_3_ex_2.1.png)

In [3]:
#exe2.1
M = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
M_transpose = M.T
print ("le matrice M est\n", M)
print("le shape de M est", M.shape)
print ("le nombre de dimensions de M est", M.ndim)
print("le transposé de M est\n", M_transpose)
print("le shape de M transposé est", M_transpose.shape)

le matrice M est
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
le shape de M est (3, 3)
le nombre de dimensions de M est 2
le transposé de M est
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
le shape de M transposé est (3, 3)


In [4]:
#exe 2.2
A =np.array([[1,2],
             [0,3],
             [4,5]])
B =np.array([[6,7,8],
             [9,10,11]])

C = A@ B
print("le matrice A est\n", A)
print("le matrice B est\n", B)
print("le produit de A et B est\n", C)

le matrice A est
 [[1 2]
 [0 3]
 [4 5]]
le matrice B est
 [[ 6  7  8]
 [ 9 10 11]]
le produit de A et B est
 [[24 27 30]
 [27 30 33]
 [69 78 87]]


## ![ex3.1](./tmp/lab_3_ex3.1.png)

In [5]:
#exe 3.1
A= np.array([[2,1],
            [1,-3]])
b = np.array([[7],[-7]])
x = np.linalg.solve(A,b)
print("la solution de Ax=b est", x)

b_cap = A @ x
print("la vérification de Ax=b donne b_cap=", b_cap)

la solution de Ax=b est [[2.]
 [3.]]
la vérification de Ax=b donne b_cap= [[ 7.]
 [-7.]]


In [6]:
# exe 3.2
A_inv = np.linalg.inv(A)
print("l'inverse de A est\n", A_inv)
x_2 = A_inv @ b
print("la solution de Ax=b en utilisant l'inverse de A est", x_2)
print("la methode de solve utilse la methode de gauss elimination pour trouver la solution de Ax=b,\n tandis que l'utilisation de l'inverse de A est une méthode plus générale mais moins efficace numériquement.")

l'inverse de A est
 [[ 0.42857143  0.14285714]
 [ 0.14285714 -0.28571429]]
la solution de Ax=b en utilisant l'inverse de A est [[2.]
 [3.]]
la methode de solve utilse la methode de gauss elimination pour trouver la solution de Ax=b,
 tandis que l'utilisation de l'inverse de A est une méthode plus générale mais moins efficace numériquement.


## ![ex4.1](./tmp/Lab_3_ex4.1.png)

In [7]:
# exe 4.1
C = np.array([[4,1],
              [1,4]])
lamdas,v = np.linalg.eig(C)
print("les valeurs propres de C sont", lamdas)
print("les vecteurs propres de C sont\n", v)

les valeurs propres de C sont [5. 3.]
les vecteurs propres de C sont
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [8]:
# exe 4.2
v1 = v[:,0]
print("le premier vecteur propre est", v1)
print("la shape de v1 est", v1.shape)
lambda_1 = lamdas[0]
print ("la première valeur propre est", lambda_1)
Cv1 = C@ v1
print("le produit de C et v1 est", Cv1)
lambda1_v1 = lambda_1 * v1
print("le produit de la première valeur propre et v1 est", lambda1_v1)

print("On peut voir que Cv1 et lambda1_v1 sont égaux, \nce qui confirme la définition des valeurs propres et des vecteurs propres.")

le premier vecteur propre est [0.70710678 0.70710678]
la shape de v1 est (2,)
la première valeur propre est 5.0
le produit de C et v1 est [3.53553391 3.53553391]
le produit de la première valeur propre et v1 est [3.53553391 3.53553391]
On peut voir que Cv1 et lambda1_v1 sont égaux, 
ce qui confirme la définition des valeurs propres et des vecteurs propres.


In [13]:
def f(x,y):
    return 10+x+y

a = np.fromfunction(f,(3,4),dtype=int)
a22 = a[:,2]
print("l'élément a[2,2] est", a22)
print(a22.shape )


l'élément a[2,2] est [12 13 14]
(3,)
